spring.datasource.username=db_name
spring.datasource.password=123456

spring.mail.username=email@email.com
spring.mail.password=app-password

jwt.secret=MINHA_CHAVE_SUPER_SECRETA_123456789
jwt.expiration=1000000